
#import <tag/aifffile.h>
#import <tag/aiffproperties.h>
#import <tag/apefile.h>
#import <tag/apefooter.h>
#import <tag/apeitem.h>
#import <tag/apeproperties.h>
#import <tag/apetag.h>
#import <tag/asfattribute.h>
#import <tag/asffile.h>
#import <tag/asfpicture.h>
#import <tag/asfproperties.h>
#import <tag/asftag.h>
#import <tag/attachedpictureframe.h>
#import <tag/audioproperties.h>
#import <tag/chapterframe.h>
#import <tag/commentsframe.h>
#import <tag/dsdiffdiintag.h>
#import <tag/dsdifffile.h>
#import <tag/dsdiffproperties.h>
#import <tag/dsffile.h>
#import <tag/dsfproperties.h>
#import <tag/eventtimingcodesframe.h>
#import <tag/fileref.h>
#import <tag/flacfile.h>
#import <tag/flacmetadatablock.h>
#import <tag/flacpicture.h>
#import <tag/flacproperties.h>
#import <tag/generalencapsulatedobjectframe.h>
#import <tag/id3v1genres.h>
#import <tag/id3v1tag.h>
#import <tag/id3v2.h>
#import <tag/id3v2extendedheader.h>
#import <tag/id3v2footer.h>
#import <tag/id3v2frame.h>
#import <tag/id3v2framefactory.h>
#import <tag/id3v2header.h>
#import <tag/id3v2synchdata.h>
#import <tag/id3v2tag.h>
#import <tag/infotag.h>
#import <tag/itfile.h>
#import <tag/itproperties.h>
#import <tag/modfile.h>
#import <tag/modfilebase.h>
#import <tag/modproperties.h>
#import <tag/modtag.h>
#import <tag/mp4atom.h>
#import <tag/mp4coverart.h>
#import <tag/mp4file.h>
#import <tag/mp4item.h>
#import <tag/mp4itemfactory.h>
#import <tag/mp4properties.h>
#import <tag/mp4tag.h>
#import <tag/mpcfile.h>
#import <tag/mpcproperties.h>
#import <tag/mpegfile.h>
#import <tag/mpegheader.h>
#import <tag/mpegproperties.h>
#import <tag/oggfile.h>
#import <tag/oggflacfile.h>
#import <tag/oggpage.h>
#import <tag/oggpageheader.h>
#import <tag/opusfile.h>
#import <tag/opusproperties.h>
#import <tag/ownershipframe.h>
#import <tag/podcastframe.h>
#import <tag/popularimeterframe.h>
#import <tag/privateframe.h>
#import <tag/relativevolumeframe.h>
#import <tag/rifffile.h>
#import <tag/s3mfile.h>
#import <tag/s3mproperties.h>
#import <tag/speexfile.h>
#import <tag/speexproperties.h>
#import <tag/synchronizedlyricsframe.h>
#import <tag/tableofcontentsframe.h>
#import <tag/tag.h>
#import <tag/taglib.h>
#import <tag/taglib_export.h>
#import <tag/tbytevector.h>
#import <tag/tbytevectorlist.h>
#import <tag/tbytevectorstream.h>
#import <tag/tdebuglistener.h>
#import <tag/textidentificationframe.h>
#import <tag/tfile.h>
#import <tag/tfilestream.h>
#import <tag/tiostream.h>
#import <tag/tlist.h>
#import <tag/tlist.tcc>
#import <tag/tmap.h>
#import <tag/tmap.tcc>
#import <tag/tpicturetype.h>
#import <tag/tpropertymap.h>
#import <tag/trueaudiofile.h>
#import <tag/trueaudioproperties.h>
#import <tag/tstring.h>
#import <tag/tstringlist.h>
#import <tag/tvariant.h>
#import <tag/tversionnumber.h>
#import <tag/uniquefileidentifierframe.h>
#import <tag/unknownframe.h>
#import <tag/unsynchronizedlyricsframe.h>
#import <tag/urllinkframe.h>
#import <tag/vorbisfile.h>
#import <tag/vorbisproperties.h>
#import <tag/wavfile.h>
#import <tag/wavpackfile.h>
#import <tag/wavpackproperties.h>
#import <tag/wavproperties.h>
#import <tag/xingheader.h>
#import <tag/xiphcomment.h>
#import <tag/xmfile.h>
#import <tag/xmproperties.h>
