// Copyright Ryan Francesconi. All Rights Reserved. Revision History at https://github.com/ryanfrancesconi/SPFKMetadata

import Foundation

extension TagKey {
    /// Return the associated ID3v2 label or TXXX if it is a non-standard (but documented) frame
    public var id3Frame: String? {
        // condensed to allow easy sorting
        switch self {
        case .album: return "TALB"
        case .albumArtist: return "TPE2"
        case .albumArtistSort: return "TSO2"
        case .albumSort: return "TSOA"
        case .artist: return "TPE1"
        case .artistSort: return "TSOP"
        case .artistWebpage: return "WOAR"
        case .audioSourceWebpage: return "WOAS"
        case .bpm: return "TBPM"
        case .comment: return "COMM"
        case .compilation: return "TCMP"
        case .composer: return "TCOM"
        case .composerSort: return "TSOC"
        case .conductor: return "TPE3"
        case .copyright: return "TCOP"
        case .copyrightURL: return "WCOP"
        case .date: return "TDRC"
        case .discNumber: return "TPOS"
        case .discSubtitle: return "TSST"
        case .encodedBy: return "TENC"
        case .encoding: return "TSSE"
        case .encodingTime: return "TDEN"
        case .fileWebpage: return "WOAF"
        case .filyType: return "TFLT"
        case .genre: return "TCON"
        case .grouping: return "GRP1"
        case .initialKey: return "TKEY"
        case .instrumentation: return "TXXX"
        case .isrc: return "TSRC"
        case .keywords, .podcastKeywords: return "TXXX"
        case .label: return "TPUB"
        case .language: return "TLAN"
        case .length: return "TLEN"
        case .lyricist: return "TEXT"
        case .lyrics: return "USLT"
        case .media: return "TMED"
        case .mood: return "TMOO"
        case .movementName: return "MVNM"
        case .movementNumber: return "MVIN"
        case .originalAlbum: return "TOAL"
        case .originalArtist: return "TOPE"
        case .originalDate: return "TDOR"
        case .originalFilename: return "TOFN"
        case .originalLyricist: return "TOLY"
        case .owner: return "TOWN"
        case .paymentWebpage: return "WPAY"
        case .playlistDelay: return "TDLY"
        case .podcast: return "PCST"
        case .podcastCategory: return "TCAT"
        case .podcastDesc: return "TDES"
        case .podcastID: return "TGID"
        case .podcastURL: return "WFED"
        case .producedNotice: return "TPRO"
        case .publisherWebpage: return "WPUB"
        case .radioStation: return "TRSN"
        case .radioStationOwner: return "TRSO"
        case .radioStationWebpage: return "WORS"
        case .releaseDate: return "TDRL"
        case .remixer, .arranger: return "TPE4"
        case .subtitle: return "TIT3"
        case .taggingDate: return "TDTG"
        case .title: return "TIT2"
        case .titleSort: return "TSOT"
        case .trackNumber: return "TRCK"
        case .work: return "TIT1"

        default: return nil
        }
    }
}
