
name: build

on:
  push:
    branches: [ "main, development" ]
  pull_request:
    branches: [ "main, development" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
